merger: bare
sources:
  - name: Pets_V1
    handler:
      openapi:
        source: ../swagger/pets.v1.json
        endpoint: >-
          http://localhost:8801
    transforms:
      - namingConvention:
          mode: bare
          typeNames: pascalCase
          enumValues: upperCase
          fieldNames: camelCase
          fieldArgumentNames: camelCase
