merger: bare
sources:
  - name: Pets_V1
    handler:
      openapi:
        source: ../swagger/pets.v1.json
        endpoint: >-
          http://localhost:4001
    transforms:
      - rename:
          mode: bare
          renames:
            - from:
                type: ServerError
              to:
                type: EvilError
